# These are supported funding model platforms

github: [lixuliu]
ko_fi: lixuliu
# Open Collective: opencollective
# Tidelift: tidelift
# Community Bridge: communitybridge
# Liberapay: liberapay
# IssueHunt: issuehunt
# Otechie: otechie
# Custom: https://www.paypal.me/lixuliu
